name: 'Terraform CI'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4

      - name: 'Set up Google Cloud credentials'
        run: echo "${{ secrets.TERRAFORM_KEY }}" > $HOME/gcloud-key.json

      

      - name: 'Terraform Init'
        run: terraform -chdir=./terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.TERRAFORM_KEY }}

      - name: 'Terraform Validate'
        run: terraform -chdir=./terraform validate
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.TERRAFORM_KEY }}

      - name: 'Terraform Plan'
        run: terraform -chdir=./terraform plan -var="google_credentials=${{ secrets.TERRAFORM_KEY }}"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.TERRAFORM_KEY }}

      - name: 'Terraform Apply'
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=./terraform apply -auto-approve -var="google_credentials=${{ secrets.TERRAFORM_KEY }}"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.TERRAFORM_KEY }}
